# Site settings
title: A portfolio site that's supposed to show that I have web developer skills?
description: A portfolio site that's supposed to show that I have skills?
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Shwetha Jayaraj
user_description: It's currently a work in progress! Check back soon :)
user_title: Software Developer
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
