# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shwetha Jayaraj
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my website! It still is a bit of work in progress till now but until then enjoy the different layouts and designs I'm trying to code for this website :) 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  shwetha729

# Build settings
markdown: kramdown

